### ISSUE TITLE
Theming / layout issue for multiple 'Media with Text' blocks

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#13]
on the subsite page https://production.localgovdrupal.org/about-lgd/people

I've added multiple  'Media with Text' blocks. 
first 5 were all ok. 
After adding the 6th (Kate Hurr) the spacing between all blocks appears borked. 

(all images are 200x200px so not sure why some display slightly different widths, possily due to text length or Drupal cropping, but will probably get some new images from people anyway, and may greyscale them all)

**Comment by MichaelDCR** [comment]
ok, if I add more text (or empty text) so it appears on 6 lines, then the spacing comes back

can live with that!

Close issue or leave it as one for future attention?

**Comment by msayoung** [comment]
It's ok, I've added some styles to keep them in line. :)

**Comment by MichaelDCR** [comment]
you are the best
