### ISSUE TITLE
Sitebuild: sidebar menus ordering

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#14]
The Sidebar sub-menus currently order by placing the most recently edited (revision) subsite page in that section at the bottom of the list, i.e. making an edit changes the order

Is there a way we can control the order, or if not then make it alphabetical?

**Comment by msayoung** [comment]
Hey @MichaelDCR 
I've just updated permissions. 
Now when you go to a subsite overview page you should see a Children option which lets you reorder the child pages. 
Enjoy!
![image](https://user-images.githubusercontent.com/3852805/133818032-cdb1424c-8199-4ab7-8777-4eb76c46c213.png)

**Comment by MichaelDCR** [comment]
Fab!
