### ISSUE TITLE
RSS feed of the /news newsroom?

### ISSUE THREAD

**Issue by jpoesen** [localgovdrupal/localgovdrupal.org#153]
Hi all.

I was wondering if an RSS feed for `/news` is available.

Assuming /news is an LGD newsroom I tried `/news/7/feed.rss` (7 being the newsroom nid) but that doesn't seem to exist.

If there's no feed available, I can build one myself with views but then I'd need (temporary) admin access. Not sure about the policy around this.

Thanks.

**Comment by ekes** [comment]
Don't think we added an update hook and this site will predate this https://github.com/localgovdrupal/localgov_news/pull/104 I guess.

**Comment by msayoung** [comment]
I've added this to the site now.

**Comment by jpoesen** [comment]
Works great.
Thanks so much for the quick solution!
