### ISSUE TITLE
Sitebuild: editing footer blocks

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#16]
Hi Maria

I am able to edit the 'lower footer second' block, but it does not save my edits. Or rather it saved the first time (couple of times?) that I edited it but the many attempts since. 

Can change the block Title, but edits to Slogan and Content do not save. 

Tried this a few times last night, and checked this morning, so pretty sure it's not a browser / varnish caching issue.

**Comment by msayoung** [comment]
When I masquerade as you I can edit it. 

I'm going to the Block Layout: https://production.localgovdrupal.org/admin/structure/block
On the block called "This site is built with LocalGov Drupal"  clicking Configure

Editing the Content, or the Slogan fields
Pressing Save. 

(The title field is just the administrative title so won't change on the frontend)

**Comment by MichaelDCR** [comment]
This is weird. I can see your edit which includes 'again.

I then edit it to have:

Content:     Created by councils, for councils.
Footer slogan:    This site is built with LocalGov Drupal

but it just reverts to an old version of:

 Content:     Created by councils, for councils.
Footer slogan:    LocalGov Drupal. Created by councils, for councils.

I CAN change the Title (and if I toggle the display, the title shows)

**Comment by MichaelDCR** [comment]
Tried in FF too with same result. 

It's not browser caching - tried random text, history cleared etc

**Comment by msayoung** [comment]
does the same for me too now. will investigate

**Comment by MichaelDCR** [comment]
just to note that I am able to edit the 'Homepage special' block fine

**Comment by msayoung** [comment]
@MichaelDCR - i think these should now update normally

can you checK?

**Comment by MichaelDCR** [comment]
working

**Comment by MichaelDCR** [comment]
sorry @msayoung - Will has requested an edit to this

instead of:  Created by councils, for councils.

now: The publishing platform created by councils, for councils.

**Comment by msayoung** [comment]
Sure thing. 
How's that now.

**Comment by MichaelDCR** [comment]
thanks!
