### ISSUE TITLE
Confirm list of Councils to mention as part of LGD

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#18]
sent to Slack instead

**Comment by willguv** [comment]
These are all fine to use:

Bracknell Forest **(not Bracknell)**
Brighton & Hove **(not Brighton)**
Croydon
Cumbria
Hammersmith & Fulham
Kensington & Chelsea
Lambeth
Luton
London Councils
Milton Keynes
Redcar & Cleveland
Sheffield
Tamworth
Waltham Forest
Westminster
(and 2 councils we can't mention yet)

I'm checking the others and will update the list as I go

**Comment by willguv** [comment]
@MichaelDCR I'm waiting for 2 more councils to get back to me - have sent a reminder email to both just now

**Comment by msayoung** [comment]
Gonna mark this closed for now.
