### ISSUE TITLE
Shop Window Website: write 'story of LGD'

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#2]
first draft required giving as brief or fulsome a history as you want 

if it is long will be a separate page, otherwise will go on About landing page 

- roots
- funding
- success
- go big on expertise 

MW can add all the Sprints and briefly review what they achieved (each has a blog to link to and take the content from)

**Comment by MichaelDCR** [comment]
Drive folder for drafts - https://drive.google.com/drive/folders/1uDCOKAP6-fmq_zPgXDKHfCK-9_iowJwK

**Comment by willguv** [comment]
@MichaelDCR this is good enough to publish I think

https://docs.google.com/document/d/1D5e0t0ibHfncQA80bZ5gv4bNDTb_8DxsvkYga7f9jfc/edit?usp=sharing

I'll do the roll call separately when we cover the people page
