### ISSUE TITLE
Video embeds (enhancement)

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#21]
Not putting this into the current sprint as it is non-critical but noting it as something to enhance the site. 

There is a video embed content type, but it displays very small, due to the default aspect ratio or something.

Have left an example in the site for now, but will remove before launch - https://production.localgovdrupal.org/drupal-for-councils/local-digital-declaration

**Comment by msayoung** [comment]
I think we fixed this, didnt we @MichaelDCR ?

**Comment by MichaelDCR** [comment]
We as in You, yes we did!

Strictly speaking can't use YT embeds due to cookie consent but hey
