### ISSUE TITLE
Typography review 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgovdrupal.org#36]
Review headings, copy, spacing of the site now that it has content in.

**Comment by MichaelDCR** [comment]
@msayoung 

It's a design thing, so not sure about me dictating this, but I would much prefer 2rem rather than 1.5rem

h2, h3, h4, h5, h6, .heading {
    margin-top: 2rem;
}

**Comment by msayoung** [comment]
I've increased it to 1.75rem 
and limited that to headings within the body field. 
I suspect this may need some more tweaking in time, but let's go with this for now

**Comment by MichaelDCR** [comment]
thanks :)
