### ISSUE TITLE
Text for 'slogan' and 'blurb' header blocks

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#41]
Slogan: 
The publishing platform created by councils, for councils.
(as now but with a full stop)

Blurb:
LocalGov Drupal is a publicly owned asset that delivers a better digital experience for citizens, improves service outcomes, and saves money.

**Comment by msayoung** [comment]
are they right now @MichaelDCR ? 
I still need to make them more editable going forward, but hopefully we're good for now.

**Comment by MichaelDCR** [comment]
Hi @msayoung - yes they are correct, closing issue
