### ISSUE TITLE
SEO of main site

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#45]
once @finnlewis gives me access to Meta Tags

**Comment by finnlewis** [comment]
@MichaelDCR 

You should now be able to set meta tags per content node: 

![image](https://user-images.githubusercontent.com/326588/135109162-e188789a-020d-4eed-bbeb-bc7d11ecb7be.png)

If you need to review the defaults, we'll need to wrap this up in config, so will need to co-ordinate.

**Comment by MichaelDCR** [comment]
all good, thanks @finnlewis
