### ISSUE TITLE
add links to Twitter / YT channels

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#51]
find editorial places, eg About as well as anything contextual 

probably needs adding to Footer too

will also have linkedin profile good enough to link to soon

**Comment by msayoung** [comment]
@MichaelDCR are you planning to add footer menu items? 
Just wondering if we need space for both in the footer ?

**Comment by msayoung** [comment]
Also, the first point - "find editorial places" - is that for you or for me :)

**Comment by MichaelDCR** [comment]
Labelled icon para type / 3 column - all pages

or use Subscribe block? has social media links - available on Subsite Overview pages

**Comment by MichaelDCR** [comment]
added to Resources and About using Labelled Icon - only available on Overview pages
