### ISSUE TITLE
fix Sitemap

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#53]
https://localgovdrupal.org/sitemap.xml

Currently points to http versions of Production sub-domain pages

**Comment by finnlewis** [comment]
Did you mean to close this @MichaelDCR ?

**Comment by MichaelDCR** [comment]
yes @finnlewis - Maria rebuilt it and all good now

**Comment by finnlewis** [comment]
I've just regenerated the sitemap, looking better? 
https://localgovdrupal.org/sitemap.xml

**Comment by finnlewis** [comment]
Hmmm, it wasn't, until I rebuilt it

**Comment by MichaelDCR** [comment]
it was, honest - you may have had a cached copy?

**Comment by finnlewis** [comment]
So it might be being updated from cron, without knowing it is on https.

Worth keeping an eye on

**Comment by MichaelDCR** [comment]
ok, let's keep open then

**Comment by finnlewis** [comment]
Yeah - look now - I just regenerated with drush

**Comment by MichaelDCR** [comment]
ouch

**Comment by finnlewis** [comment]
Should be all good https://localgovdrupal.org/sitemap.xml

**Comment by MichaelDCR** [comment]
nice one - if it does break we should pick it up via Search Console
