### ISSUE TITLE
Google Search Console

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#54]
add a Google Search Console for the site, when #53 sitemap is fixed 

will need DEV to drop a file into root, or add a DNS record

**Comment by MichaelDCR** [comment]
@msayoung  or @finnlewis - can you upload this empty html file to Root - https://u.pcloud.link/publink/show?code=XZIXrtXZpPUxQopmTu4i4Ab7mrc3qhcV5V9k

i.e. so it is available at https://localgovdrupal.org/google70a56eebb76fad34

I'll then create the Search Console account once the sitemap #53 is ok, and add support@agile.coop as an admin

**Comment by finnlewis** [comment]
@MichaelDCR It is at https://localgovdrupal.org/google70a56eebb76fad34.html

**Comment by MichaelDCR** [comment]
thanks finn

**Comment by MichaelDCR** [comment]
Search Console created, sitemap submitted, support@agile.coop added
