### ISSUE TITLE
content - migrating from D8 / D7

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#55]
as it has been raised by a few councils

**Comment by andybroomfield** [comment]
Starting point could be [localgov_legacy_migration](https://github.com/localgovdrupal/localgov_legacy_migration) module that was originally used (and is currently at BHCC) as a base for the migration. This was designed with the field mappings from the legacy code, but also serves as some initial documentation on how to map fields for a Drupal migration.

**Comment by MichaelDCR** [comment]
thanks @andybroomfield - I'm going to close this as it seems out of scope for now, but will keep a record of content enhancements on Drive
