### ISSUE TITLE
Tweak to quotes

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgovdrupal.org#57]
"Quotes - we are having to use them in some places without a name, and in those instances the quote lacks the speech bubble line. Can we add such a line or a closing quote mark. For example see https://localgovdrupal.org/features"

Sally is doing some designs, will update when needed.

**Comment by msayoung** [comment]
Quote styling ready for review on the stage site. 
Both types here: https://stage.localgovdrupal.org/features

**Comment by MichaelDCR** [comment]
Great - the orange one please - same design as where there is a named quotee

**Comment by msayoung** [comment]
hi @MichaelDCR 

So you can use the quote paragraph type with or without the attribution. the bottom line now stays in place without a name. 

The blockquote style (with the purple) is for quotes within the WYSIWYG. 

does that make sense? 

M

**Comment by ghost** [comment]
Like both styles. Cheers.

**Comment by msayoung** [comment]
cool, I will merge
