### ISSUE TITLE
Sitebuild: Add involved councils footer

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgovdrupal.org#8]

**Comment by msayoung** [comment]
Hey @MichaelDCR @willguv @TJHDCR 

I've added a participating councils block to the footer. 

You can add new ones by going to **admin > content > media > add media > council logo**

I think they will display in the order they are added. 
Let me know how you get on.

**Comment by MichaelDCR** [comment]
can we lift them from Sally's figma?

**Comment by msayoung** [comment]
@MichaelDCR the logos appear in the order they were added. 
I'm going to close this issue now
