### ISSUE TITLE
Sitebuild: homepage blocks

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgovdrupal.org#9]

**Comment by msayoung** [comment]
I've added some fancy blocks on the homepage for the Quote and the 16 Councils .... block. 
You should be able to edit the content here: https://production.localgovdrupal.org/admin/structure/block/block-content
but let me know if you need help. 
It still needs some styling at mobile. 
M

**Comment by finnlewis** [comment]
Maria is just fixing these to work at mobile widths.

**Comment by msayoung** [comment]
I think this is ok now.
